substitutions:
  device_name: schalter-kitchen
  friendly_name: Schalter KÃ¼che
  ota_password: !secret ota_password
  fallback_wifi_pwd: !secret fallback_wifi_pwd
  light_entity: light.philips_915005996401_light
  bt_proxy: "true"

packages:
  minir4: !include common/minir4.yaml
