substitutions:
  device_name: schalter-deckenlampe-th
  friendly_name: Schalter Deckenlampe Treppenhaus
  ota_password: !secret ota_password
  fallback_wifi_pwd: !secret fallback_wifi_pwd
  light_entity: light.deckenlampe_treppenhaus
  bt_proxy: "false"

packages:
  minir4: !include common/minir4.yaml
