substitutions:
  device_name: schalter-bar
  friendly_name: Schalter Bar
  ota_password: !secret ota_password
  fallback_wifi_pwd: !secret fallback_wifi_pwd
  light_entity: light.barlampe
  bt_proxy: "false"

packages:
  minir4: !include common/minir4.yaml
